name: RandomHeadPlugin
main: dev.depressy.randomhead.RandomHeadPlugin
version: 1.0
api-version: 1.20
author: Sean
description: Gives players random HeadDatabase heads every 2 hours, with a GUI claim system.

commands:
  claim:
    description: Open your head claim GUI
    usage: /claim
    permission: randomhead.claim
  rhd:
    description: Instantly get a random head (OP only)
    usage: /rhd
    permission: randomhead.rhd

permissions:
  randomhead.claim:
    description: Allows use of /claim
    default: true

  randomhead.rhd:
    description: Allows use of /rhd (OP only)
    default: op
