name: RandomHead
version: 1.0
main: dev.depressy.randomhead.RandomHeadPlugin
api-version: 1.20
description: Gives players a random head every 2 hours of active playtime
author: depressy

commands:
  rhd:
    description: Manually give a head (OP only)
    usage: /rhd
  cooldown:
    description: Check your head cooldown
    usage: /cooldown
